# Generated by Django 6.0.2 on 2026-05-09 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='Train number must be 5 or 6 digits.', regex='^\\d{5,6}$')], verbose_name='Train Number')),
                ('train_name', models.CharField(db_index=True, max_length=255, verbose_name='Train Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['train_number'],
            },
        ),
    ]
