# Generated by Django 6.0.2 on 2026-02-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('reset_password', 'Reset Password')], default='login', max_length=20),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone_number', 'code', 'purpose'], name='accounts_ot_phone_n_ae761e_idx'),
        ),
    ]
