# Generated by Django 6.0.2 on 2026-03-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_uuid'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otp',
            name='accounts_ot_phone_n_ae761e_idx',
        ),
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(default='login', max_length=20),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone_number', 'code'], name='accounts_ot_phone_n_11444c_idx'),
        ),
    ]
