# Generated by Django 6.0.2 on 2026-03-29 19:35

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_otp_accounts_ot_phone_n_ae761e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=70, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='Name should contain only letters and spaces.', regex='^[A-Za-z ]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', validators=[accounts.models.User.validate_image]),
        ),
    ]
