# Generated by Django 6.0.2 on 2026-05-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_email_alter_user_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('porter', 'Porter'), ('admin', 'Admin')], db_index=True, max_length=10),
        ),
    ]
