# Generated by Django 6.0.2 on 2026-03-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stnCode', models.CharField(max_length=10, unique=True)),
                ('stnName', models.CharField(max_length=120)),
                ('stnCity', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['stnName'],
                'indexes': [models.Index(fields=['stnCode'], name='stations_st_stnCode_c89cc2_idx'), models.Index(fields=['stnName'], name='stations_st_stnName_61924f_idx'), models.Index(fields=['stnCity'], name='stations_st_stnCity_5b6ed1_idx')],
            },
        ),
    ]
