# Generated by Django 6.0.2 on 2026-05-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['stn_name']},
        ),
        migrations.RemoveIndex(
            model_name='station',
            name='stations_st_stnCode_c89cc2_idx',
        ),
        migrations.RemoveIndex(
            model_name='station',
            name='stations_st_stnName_61924f_idx',
        ),
        migrations.RemoveIndex(
            model_name='station',
            name='stations_st_stnCity_5b6ed1_idx',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='stnCity',
            new_name='stn_city',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='stnCode',
            new_name='stn_code',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='stnName',
            new_name='stn_name',
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['stn_code'], name='stations_st_stn_cod_bf8809_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['stn_name'], name='stations_st_stn_nam_501576_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['stn_city'], name='stations_st_stn_cit_2c0092_idx'),
        ),
    ]
